name: Generate Burndown Chart

on:
  schedule:
    - cron: "0 12 * * *"  # Executa todo dia ao meio-dia UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  burndown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install matplotlib requests

      - name: Run script
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: python burndown_chart.py

      - name: Commit and push chart
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add burndown_chart.png
          git commit -m "Updated Burndown Chart" || echo "No changes to commit"
          git push
